TWEAK_NAME := RoseSafari
RoseSafari_FILES += Tweak.x
RoseSafari_FRAMEWORKS += UIKit
RoseSafari_CFLAGS += -fobjc-arc
RoseSafari_LIBRARIES += Rose
RoseSafari_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk