TWEAK_NAME := RoseTwitter
RoseTwitter_FILES += Tweak.x
RoseTwitter_FRAMEWORKS += UIKit
RoseTwitter_CFLAGS += -fobjc-arc
RoseTwitter_LIBRARIES += Rose
RoseTwitter_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk