include $(THEOS)/makefiles/common.mk

export ADDITIONAL_CFLAGS = -I$(THEOS_PROJECT_DIR)/libRose/include -DTHEOS_LEAN_AND_MEAN
export ADDITIONAL_LDFLAGS = -L$(THEOS_OBJ_DIR)
SUBPROJECTS = Apollo Calculator Instagram Music Phone Safari Spotify Twitter

include $(THEOS_MAKE_PATH)/aggregate.mk
