TWEAK_NAME := RoseSpotify
RoseSpotify_FILES += Tweak.x
RoseSpotify_FRAMEWORKS += UIKit
RoseSpotify_CFLAGS += -fobjc-arc
RoseSpotify_LIBRARIES += Rose
RoseSpotify_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk