TWEAK_NAME := RoseMusic
RoseMusic_FILES += Tweak.x
RoseMusic_FRAMEWORKS += UIKit
RoseMusic_CFLAGS += -fobjc-arc
RoseMusic_LIBRARIES += Rose
RoseMusic_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk