TWEAK_NAME := Rose
Rose_FILES += Tweak.x
Rose_CFLAGS += -fobjc-arc -Iinclude -DTHEOS_LEAN_AND_MEAN
Rose_LDFLAGS += -L$(THEOS_OBJ_DIR)
Rose_LIBRARIES += Rose
Rose_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk