TWEAK_NAME := RoseInstagram
RoseInstagram_FILES += Tweak.x
RoseInstagram_FRAMEWORKS += UIKit
RoseInstagram_CFLAGS += -fobjc-arc
RoseInstagram_LIBRARIES += Rose
RoseInstagram_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk