TWEAK_NAME := RosePhone
RosePhone_FILES += Tweak.x
RosePhone_FRAMEWORKS += UIKit
RosePhone_CFLAGS += -fobjc-arc
RosePhone_LIBRARIES += Rose
RosePhone_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk