TWEAK_NAME := RoseApollo
RoseApollo_FILES += Tweak.x
RoseApollo_FRAMEWORKS += UIKit
RoseApollo_CFLAGS += -fobjc-arc
RoseApollo_LIBRARIES += Rose
RoseApollo_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk