TWEAK_NAME = RoseCalculator
RoseCalculator_FILES = Tweak.x
RoseCalculator_FRAMEWORKS = UIKit
RoseCalculator_CFLAGS = -fobjc-arc
RoseCalculator_LIBRARIES = Rose
RoseCalculator_EXTRA_FRAMEWORKS = Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk